### PR TITLE
Fixed xo formatter (closes #203, closes #201)

### LINKED ISSUE #201: Rewrite xo to use --stdin-filename option
So we can use ignores option in package.json xo configuration, per https://github.com/sindresorhus/xo/issues/244

### LINKED ISSUE #203: xo formatter is currently broken
due to the issues here, the `xo` support is not working currently:

<https://github.com/sindresorhus/xo/issues/245>
<https://github.com/eslint/eslint/issues/9111>

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
@sindresorhus once this is accepted you can use overrides and ignores options now with this plugin 👍 !

**Comment by niftylettuce** [comment]
Thanks @Chiel92

**Comment by aureooms** [comment]
This breaks applying the local `xo` config (inside `package.json`), I am running `xo@0.38.2`.

**Comment by aureooms** [comment]
And using `--stdin-filename` instead of `--stdin` causes the same problem.

**Pull request merged**
