### PR TITLE
Added an option to highlight/mark syntactically not correct lines

### PR DESCRIPTION
**Pull request by umitkablan**
This will let user change those lines manually and see the diff if s/he wants.

### CODE REVIEW

**Comment by Chiel92** [comment]
I tried to run your code, but with no luck:

```
Error detected while processing function <SNR>49_TryAllFormatters[48]..<SNR>49_TryFormatterPython3:
line  102:
Traceback (most recent call last):
  File "<string>", line 49, in <module>
NameError: name 'NamedTemporaryFile' is not defined
```

**Comment by umitkablan** [comment]
Ops sorry I forgot to tell you that I couldn't test it in with python3. I could only test python section and copy-pasted to python3.
Honestly, it felt weird to copy paste blindly, but, it also seems unnecessary to have python dependency for a minor task. I think we can convert python code to vimscript easily - like many other plugins with pure vimscript making linter-based operations.

**Comment by Chiel92** [comment]
> I think we can convert python code to vimscript easily - like many other plugins with pure vimscript making linter-based operations.

If you mean converting the entire plugin to vim script, then no, this cannot be done easily. Vim-autoformat used to be vim-script only, but we needed to migrate to python code for technical reasons related to the calling of the format program.

> Ops sorry I forgot to tell you that I couldn't test it in with python3.

It shouldn't be too hard to get your hands on a vim that can do both. My vim installation (on windows) can do either 2 or 3, just whichever is called first.

**Comment by umitkablan** [comment]
Python3 code works now (many encoding issues pheew).

As far as I can see you are using python to stream-in/out lines - which I think some formatters are working stdin/stdout only? It is hard to imagine a unix program with stdin/out support without file in/out - generally all should be doable playing with command line switches, no? If thats the case can't we just write a small python executable that warps such "executables" and add file in/out capabilities?

As I have been trying to add Python3 support (and cannot add both at the same time) I am convinced that wout dependency is more reachable. Many plugins are rewritten to drop external dependencies and they are advertising it. So pushing the rubbish under to hoods (in a python executable wrapper) is cleaner than vice versa (adding the pythonXX codes directly in the plugin).

**Comment by Chiel92** [comment]
Still runtime errors:

```
Error detected while processing function <SNR>49_TryAllFormatters[48]..<SNR>49_TryFormatterPython3:
line  104:
Traceback (most recent call last):
  File "<string>", line 61, in <module>
  File "<string>", line 61, in <listcomp>
TypeError: Can't convert 'bytes' object to str implicitly
```

> As I have been trying to add Python3 support (and cannot add both at the same time) I am convinced that wout dependency is more reachable. Many plugins are rewritten to drop external dependencies and they are advertising it. So pushing the rubbish under to hoods (in a python executable wrapper) is cleaner than vice versa (adding the pythonXX codes directly in the plugin).

I'm not sure what you mean here. Python3 is a very common dependency. There is hardly any reason to compile vim without the python support. And to properly communicate with vim you want to use the python API, so using an external python executable is not a better option.

If you're interested, one of the reasons for introducing python code is this issue: https://github.com/Chiel92/vim-autoformat/issues/10

**Comment by umitkablan** [comment]
Hi,

It is working perfectly with brew installed macvim 8.0-172. Could you please correct it if you have Python3 experience? As the problematic line seems to be
`    for eol in possible_eols:
        lines = [splitline for line in lines for splitline in line.split(eol.encode('utf-8'))]
`
Maybe we can decompose this list comprehension in 2 loops and see where exactly it is failing. There is no problem here so I am unable to fix it easily.

**Comment by Chiel92** [comment]
I think you haven't actually tested it with python 3. 
The part `eol.encode('utf-8')` is downright wrong, since the split function cannot take a `bytes` object.
It will always fail.

E.g. try running `''.split(b',')` in a python interpreter.

**Comment by umitkablan** [comment]
`



VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 10:14:43)
MacOS X (unix) version
Included patches: 1-172
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +lambda          +mouse           +multi_lang      +profile         +statusline      +timers          +wildignore      
+arabic          +cmdline_hist    +dnd             -footer          +langmap         +mouseshape      -mzscheme        -python          -sun_workshop    +title           +wildmenu        
+autocmd         +cmdline_info    -ebcdic          +fork()          +libcall         +mouse_dec       +netbeans_intg   +python3         +syntax          +toolbar         +windows         
+balloon_eval    +comments        +emacs_tags      +fullscreen      +linebreak       -mouse_gpm       +num64           +quickfix        +tag_binary      +transparency    +writebackup     
+browse          +conceal         +eval            -gettext         +lispindent      -mouse_jsbterm   +odbeditor       +reltime         +tag_old_static  +user_commands   -X11             
++builtin_terms  +cryptv          +ex_extra        -hangul_input    +listcmds        +mouse_netterm   +packages        +rightleft       -tag_any_white   +vertsplit       -xfontset        
+byte_offset     +cscope          +extra_search    +iconv           +localmap        +mouse_sgr       +path_extra      +ruby            +tcl             +virtualedit     +xim             
+channel         +cursorbind      +farsi           +insert_expand   +lua             -mouse_sysmouse  +perl            +scrollbind      +termguicolors   +visual          -xpm             
+cindent         +cursorshape     +file_in_path    +job             +menu            +mouse_urxvt     +persistent_undo +signs           +terminfo        +visualextra     -xsmp            
+clientserver    +dialog_con_gui  +find_in_path    +jumplist        +mksession       +mouse_xterm     +postscript      +smartindent     +termresponse    +viminfo         -xterm_clipboard 
+clipboard       +diff            +float           +keymap          +modify_fname    +multi_byte      +printer         +startuptime     +textobjects     +vreplace        -xterm_save      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/opt/lua/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
`

`!!!Python 3.6.0 (default, Dec 24 2016, 08:01:42) !!!
!!![GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin!!!
!!!Type "help", "copyright", "credits" or "license" for more information.!!!
>>> ''.split(b',')
!!!Traceback (most recent call last):!!!
!!!  File "<stdin>", line 1, in <module>!!!
!!!TypeError: must be str or None, not bytes!!!
>>> ''.split(',')
['']
>>> 
`

But it works! How...

**Comment by Chiel92** [comment]
> But it works! How...

That means it doesn't hit that line of code.
I don't know what testing scenario you use, but try playing around with that.
To determine what code is actually executed, you can put print statements in the code.

**Comment by umitkablan** [comment]
The feature was for my needs anyways - won't make further efforts to merge it and apply my ideas to my fork.

Sorry for disturbing.
All the Best!

**Comment by Chiel92** [comment]
No problem!

Cheers

**Pull request closed without merging**
