### PR TITLE
fix: do not treat following "|" and strings as arguments in Autoformat command

### PR DESCRIPTION
**Pull request by kayw**
related issue: https://github.com/Chiel92/vim-autoformat/issues/124
copy from this code: https://github.com/rhysd/vim-crystal/blob/master/ftplugin/crystal.vim#L51

### CODE REVIEW

**Comment by Chiel92** [comment]
Thanks for the PR. Where can I find documentation on what this `-bar` argument does?

**Comment by kayw** [comment]
:h command-bar

**Comment by Chiel92** [comment]
Seems like a good idea. Thanks for the PR!

**Comment by kayw** [comment]
happy to see it helps

**Pull request merged**
