### PR TITLE
Add terraform fmt support

### PR DESCRIPTION
**Pull request by svenstaro**
Tested it and this appears to do the job just fine.

### CODE REVIEW

**Comment by Chiel92** [comment]
Thanks!

**Comment by prologic** [comment]
Kind of wondering whether the new formatter for Terraform is working for anyone? I pulled the latest code for `vim-autoformat` but saving my buffer seems to have no effect on the source file I'm editing. No error either.

**Comment by chtenb** [comment]
Did you execute the `:Autoformat` command?

**Comment by prologic** [comment]
> Did you execute the `:Autoformat` command?

I use this little Vim-script snippet in my `~/.vimrc`:

```#!vim
" auto-format

fun! DoAutoformat()
    " Only call Autoformat() if the b:noAutoformat variable isn't set
    if exists('b:noAutoformat')
        return
    endif
    :Autoformat
endfun

autocmd BufWritePre * call DoAutoformat()
```

**Pull request merged**
