### PR TITLE
change yapf default setting

### PR DESCRIPTION
**Pull request by WHQ25**
working yapf version: 0.8.2

### CODE REVIEW

**Comment by Chiel92** [comment]
Well, when I run that, I get

```
Formatter yapf has errors: b'yapf: "\'{based_on_style:pep8,indent_width:4}\'" is not a valid style or file path\r\n' Skipping.
```

xD

Are you running vim from the terminal though?

**Comment by WHQ25** [comment]
yes I only use vim in terminal

**Comment by Chiel92** [comment]
Ok, since I can't use python in the terminal version on windows (which I'm on) for some reason, I can't test this myself on terminal vim.

Would you care to try this out yourself in gvim on your system? Maybe there's a clue.

**Comment by WHQ25** [comment]
Well, I tested it in gvim, it works for me.

**Comment by Chiel92** [comment]
I tried it on my linux computer (ubuntu 14.04) and this solution worked for both vim and gvim. But the original definition also works there.

@cmcginty does this new solution work for you? If yes, this may be just a conflict between mac and windows.

**Comment by Chiel92** [comment]
related: https://github.com/Chiel92/vim-autoformat/issues/137#issuecomment-222916809

**Comment by Chiel92** [comment]
So on windows I get this errors message:

```
"~\.vim\bundle\vim-autoformat\samples\python.py" 208L, 8063C
Selected formatter: yapf
Formatter yapf has errors: b'yapf: "\'{based_on_style:pep8,indent_width:4}\'" is not a valid style or file path\r\n' Skipping.
Failing config: "yapf --style='{based_on_style:pep8,indent_width:4}' -l 1-208"
Definition in 'g:formatdef_yapf' was unsuccessful.
Definition in 'g:formatdef_autopep8' was successful.

```

From `"\'{based_on_style:pep8,indent_width:4}\'"` it seems that stuff is getting doubly escaped here. I need to investigate this further.

**Comment by Chiel92** [comment]
@WHQ25 @cmcginty I pushed a new definition to branch `WHQ25-fix_yapf`. Could you please check it out and see if that one works for you?

**Comment by cmcginty** [comment]
Sorry, gmail filed this issue incorrectly in my inbox. I'll test out the code tomorrow.

**Comment by cmcginty** [comment]
:+1:  works fine for me

**Pull request merged**
