### PR TITLE
Added option g:autoformat_showdiff

### PR DESCRIPTION
**Pull request by umitkablan**
If g:autoformat_showdiff flag is set then, Autoformat, instead of overwriting the buffer with formatted content, shows the diff for you to take manual actions on those lines. g:autoformat_diffcmd is the diff command to use for that purpose.

### CODE REVIEW

**Comment by Chiel92** [comment]
Thanks for the PR! Seems like a non-intrusive feature, so I'm inclined to merge this in.

Out of curiosity, what use case do you have where this  could be useful?

**Comment by umitkablan** [comment]
Thanks @Chiel92!

Well at work we have a coding guideline that is also "defined" by gofmt/clang-format which is very good to combine autocommand at write BUT sometimes it is *not welcome* when it changes other lines than you touch. Yes, not everyone is using automated formatting on write and they manually align (code reviews etc) to formatting guidelines.

So I thought to have a split on every write showing me what I have done wrong then I can manually change MY lines. Actually it would be a better feature to automatically replace only *changed* lines (utilizing some git/hg gutter plugins, changed regarding git HEAD of course) OR marking lines for a warning OR show a notifying character at sign column like syntastic/signify does.

**Comment by umitkablan** [comment]
Hi @Chiel92,

I think I've managed to use "line highlighing" for now as a better solution to my problem - so could you please wait a little for me to polish my solution? Diff showing should be considered for detailed look - simple line highlight is somehow catchier.

**Comment by Chiel92** [comment]
Sure.

**Comment by umitkablan** [comment]
PR #164 includes this - so closed.

**Pull request closed without merging**
